### ISSUE TITLE
Unexpected token => in authenticator.js 

### ISSUE THREAD

**Issue by iamrutvik** [nus-mtp/worldscope#90]
I followed instruction strictly and then when hit npm start , syntax error was thrown with

Authenticator.js:61
})().then((adapter) => adapter.getUser());
^^
SyntaxError: Unexpected token =>
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Function. (F:\worldscope-master\app_server\node_modules\rfr\lib\rfr.js:160:12)
at Object. (F:\worldscope-master\app_server\app\Router.js:12:21)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3

What should be the issue?

**Comment by ndt93** [comment]
Hi @iamrutvik, it's a ES6 syntax. You will need NodeJS version 4 at least to have ES6 support.
